version: 0.2

env:
  variables:
    AWS_REGION: us-east-1 # checkfor specific region
    AWS_ACCOUNT_ID: 452444392358  # account id
    IMAGE_REPO_NAME: foodappimages # image name
    REPOSITORY_URI: 452444392358.dkr.ecr.us-east-1.amazonaws.com/foodappimages
    IMAGE_TAG: latestbe
    
phases:
  pre_build:
    commands :
        - aws codecommit get-file --repository-name foodAppBackEndDevOps --commit-specifier FoodAppBackEnd-deploy01 --file-path Dockerfile  
  build:
    commands:
        - mvn clean package -DskipTests=true
        - mvn install
        - echo Dockerfile
        - echo Build started on `date`
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - echo Building the Docker image...
        - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
        - echo Logging in to Amazon ECR...
        - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 452444392358.dkr.ecr.us-east-1.amazonaws.com
  post_build:
    commands:
        - echo Build completed on `date`
        - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        - echo Pushing the Docker image...
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        - echo $IMAGE_REPO-NAME
        #- printf '{"ImageURI":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"}' > imageDetail.json
        - printf '{"ImageURI":"%s"}'  $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG  > imageDetail.json
artifacts:
   files:
     - 'taskdef.json'
     - 'beappspec.yaml'
     - 'Dockerfile'
     - 'image*.json'
ImageArtifact:
   files:
     - imageDetail.json
